name: Deploy Static Calculator Without Admin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show current directory
        run: |
          Write-Host "Current directory: $PWD"
        shell: powershell

      - name: Debug: Show all repo files
        run: |
          Get-ChildItem -Recurse | Select-Object FullName
        shell: powershell

      - name: Clear old deployed files
        run: |
          $target = "$env:USERPROFILE\Sites\calculator"
          if (Test-Path $target) {
            Remove-Item "$target\*" -Recurse -Force -ErrorAction SilentlyContinue
          }
        shell: powershell

      - name: Deploy calculator files
        run: |
          $source = "./WebCalculator"  # Adjust this if needed
          $target = "$env:USERPROFILE\Sites\calculator"
          New-Item -ItemType Directory -Force -Path $target
          Copy-Item -Path "$source\*" -Destination $target -Recurse -Force
        shell: powershell

      - name: List deployed files
        run: |
          Get-ChildItem "$env:USERPROFILE\Sites\calculator" -Recurse
        shell: powershell
