name: Deploy Static Calculator to IIS

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop IIS Site
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "DefaultAppPool"
        shell: powershell

      - name: Clear existing files (optional)
        run: |
          Remove-Item "C:\inetpub\wwwroot\your-app\*" -Recurse -Force -ErrorAction SilentlyContinue
        shell: powershell

      - name: Deploy static HTML app to IIS
        run: |
          New-Item -ItemType Directory -Force -Path "C:\inetpub\wwwroot\your-app"
          Copy-Item -Path "./calculator/*" -Destination "C:\inetpub\wwwroot\your-app" -Recurse -Force
        shell: powershell

      - name: Start IIS Site
        run: |
          Start-WebAppPool -Name "DefaultAppPool"
        shell: powershell

